### ISSUE TITLE
Dont forget about lab subjects

### ISSUE THREAD

**Issue by coffeeCoder69** [angadsinghsandhu/CSE-MIT-Manipal#1]
please add open source technologies lab also in 3rd sem

**Comment by angadsinghsandhu** [comment]
I have not, all coding subjects have a `practice` and `lab` folder.
I will also add the lab you mentioned today.
btw, I've heard about you Shuvam. Good to finally talk to you

**Comment by coffeeCoder69** [comment]
you r doing good work. keep it up.

**Comment by angadsinghsandhu** [comment]
You too man, keep it up.
